[package]
name = "ffgl-gpu"
version = "0.1.0"
edition.workspace = true

[dependencies]
ffgl-core = { workspace = true }
ffgl-glium = { workspace = true }
gpu-interop = { workspace = true }
gl = { workspace = true }
tracing = { workspace = true }
anyhow = { workspace = true }
